package org.ahmet.tests;

public class locator {
//    import { test, expect } from '@playwright/test';
//
//    test('test', async ({ page }) => {
//        await page.goto('https://www.saucedemo.com/');
//        await page.locator('[data-test="login-credentials"]').click();
//        await page.locator('[data-test="login-credentials"]').click();
//        await page.locator('[data-test="login-credentials"]').click();
//        await page.locator('[data-test="username"]').click();
//        await page.locator('[data-test="login-credentials"]').click();
//        await page.locator('[data-test="login-credentials"]').click();
//        await page.locator('[data-test="username"]').click();
//        await page.locator('[data-test="username"]').fill('standart_user');
//        await page.locator('[data-test="password"]').click();
//        await page.locator('[data-test="password"]').fill('secret_sauce');
//        await page.locator('[data-test="login-container"]').click();
//        await page.locator('[data-test="login-button"]').click();
//        await page.locator('[data-test="password"]').click();
//        await page.locator('[data-test="password"]').fill('secret_sauce');
//        await page.locator('[data-test="username"]').click();
//        await page.locator('[data-test="username"]').press('ArrowLeft');
//        await page.locator('[data-test="username"]').press('ArrowLeft');
//        await page.locator('[data-test="username"]').press('ArrowLeft');
//        await page.locator('[data-test="username"]').press('ArrowLeft');
//        await page.locator('[data-test="username"]').press('ArrowLeft');
//        await page.locator('[data-test="username"]').fill('standard_user');
//        await page.locator('[data-test="login-button"]').click();
//        await page.getByText('Name (A to Z)Name (A to Z)').click();
//        await page.getByText('Name (A to Z)Name (A to Z)').click();
//        await page.locator('[data-test="product-sort-container"]').selectOption('za');
//        await page.getByText('Name (Z to A)Name (A to Z)').click();
//        await page.locator('[data-test="product-sort-container"]').selectOption('lohi');
//        await page.getByText('Price (low to high)Name (A to').click();
//        await page.locator('[data-test="product-sort-container"]').selectOption('hilo');
//        await page.locator('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').click();
//        await page.locator('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').click();
//        await page.locator('[data-test="add-to-cart-sauce-labs-bike-light"]').click();
//        await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').click();
//        await page.locator('[data-test="add-to-cart-test\\.allthethings\\(\\)-t-shirt-\\(red\\)"]').click();
//        await page.locator('[data-test="add-to-cart-sauce-labs-onesie"]').click();
//        await page.locator('[data-test="shopping-cart-link"]').click();
//        await page.getByText('It\'s not every day that you').click();
//        await page.getByText('$49.99Remove').click();
//        await page.getByText('Get your testing superhero on').click();
//        await page.getByText('$15.99Remove').first().click();
//        await page.getByText('A red light isn\'t the desired').click();
//        await page.getByText('$9.99Remove').click();
//        await page.getByText('carry.allTheThings() with the').click();
//        await page.getByText('$29.99Remove').click();
//        await page.getByText('This classic Sauce Labs t-').click();
//        await page.getByText('$15.99Remove').nth(1).click();
//        await page.getByText('Rib snap infant onesie for').click();
//        await page.locator('[data-test="checkout"]').click();
//        await page.locator('[data-test="firstName"]').click();
//        await page.locator('[data-test="firstName"]').fill('ahmet');
//        await page.locator('[data-test="lastName"]').click();
//        await page.locator('[data-test="lastName"]').fill('a');
//        await page.locator('[data-test="postalCode"]').click();
//        await page.locator('[data-test="postalCode"]').fill('12345');
//        await page.locator('[data-test="continue"]').click();
//        await page.getByText('$49.99').click();
//        await page.locator('[data-test="cart-list"] div').filter({ hasText: '1Sauce Labs Fleece JacketIt\'s' }).locator('[data-test="item-quantity"]').click();
//        await page.locator('[data-test="cart-list"] div').filter({ hasText: '1Sauce Labs Bolt T-ShirtGet' }).locator('[data-test="item-quantity"]').click();
//        await page.locator('[data-test="cart-list"] div').filter({ hasText: '1Sauce Labs Bike LightA red' }).locator('[data-test="item-quantity"]').click();
//        await page.locator('[data-test="cart-list"] div').filter({ hasText: '1Sauce Labs Backpackcarry.' }).locator('[data-test="item-quantity"]').click();
//        await page.locator('[data-test="cart-list"] div').filter({ hasText: '1Test.allTheThings() T-Shirt' }).locator('[data-test="item-quantity"]').click();
//        await page.locator('[data-test="cart-list"] div').filter({ hasText: '1Sauce Labs OnesieRib snap' }).locator('[data-test="item-quantity"]').click();
//        await page.locator('[data-test="payment-info-label"]').click();
//        await page.locator('[data-test="payment-info-value"]').click();
//        await page.locator('[data-test="payment-info-value"]').click();
//        await page.locator('[data-test="shipping-info-label"]').click();
//        await page.locator('[data-test="shipping-info-value"]').click();
//        await page.locator('[data-test="total-info-label"]').click();
//        await page.locator('[data-test="subtotal-label"]').click();
//        await page.locator('[data-test="tax-label"]').click();
//        await page.locator('[data-test="total-label"]').click();
//        await page.locator('[data-test="finish"]').click();
//        await page.locator('[data-test="complete-header"]').click();
//        await page.locator('[data-test="complete-text"]').click();
//        await page.locator('[data-test="back-to-products"]').click();
//        await page.locator('[data-test="about-sidebar-link"]').click();
//        await page.goto('https://www.saucedemo.com/inventory.html');
//        await page.goto('https://www.saucedemo.com/?/inventory.html');
//        await page.goto('https://www.saucedemo.com/inventory.html');
//        await page.getByRole('button', { name: 'Open Menu' }).click();
//        await page.locator('[data-test="logout-sidebar-link"]').click();
//    });

}
